baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Megan Briers"
theme = "hugo-theme-shell"

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Megan Briers"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "meg"
  pcName = "laptop"
  workDir = "personal_dir"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  
  Hi I am Megan Briers. I'm an incoming
  MPhil student at the University of Cambridge 
  studying History and Philosophy of Science 
  and aspiring historian of 19th century astronomy.
  
  I recently graduated from the University of 
  St Andrews with a first class degree in 
  Mathematics and Computer Science.
  
  Click on the relevant links to find out more! 
  
  ✨
  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_activity"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["👱🏻‍♀️ About me", "https://www.example.com/"],
    ["✍️ History Research", "https://www.example.com/"],
    ["🖥️ Computing Work", "https://golang.org/"],
    ["📃 Academic CV", "/post/some-activity.md"],
    ["💬 Contact me", "/post/some-activity.md"],
  ]
